/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Capabilities implements org.apache.thrift.TBase<Capabilities, Capabilities._Fields>, java.io.Serializable, Cloneable, Comparable<Capabilities> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Capabilities");

  private static final org.apache.thrift.protocol.TField WORKLOAD_CONTRACT_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("workloadContractVersion", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BOUNDED_RANGE_FIELD_DESC = new org.apache.thrift.protocol.TField("boundedRange", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CapabilitiesStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CapabilitiesTupleSchemeFactory();

  public int workloadContractVersion; // required
  public boolean boundedRange; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WORKLOAD_CONTRACT_VERSION((short)1, "workloadContractVersion"),
    BOUNDED_RANGE((short)2, "boundedRange");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WORKLOAD_CONTRACT_VERSION
          return WORKLOAD_CONTRACT_VERSION;
        case 2: // BOUNDED_RANGE
          return BOUNDED_RANGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WORKLOADCONTRACTVERSION_ISSET_ID = 0;
  private static final int __BOUNDEDRANGE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WORKLOAD_CONTRACT_VERSION, new org.apache.thrift.meta_data.FieldMetaData("workloadContractVersion", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BOUNDED_RANGE, new org.apache.thrift.meta_data.FieldMetaData("boundedRange", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Capabilities.class, metaDataMap);
  }

  public Capabilities() {
  }

  public Capabilities(
    int workloadContractVersion,
    boolean boundedRange)
  {
    this();
    this.workloadContractVersion = workloadContractVersion;
    setWorkloadContractVersionIsSet(true);
    this.boundedRange = boundedRange;
    setBoundedRangeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Capabilities(Capabilities other) {
    __isset_bitfield = other.__isset_bitfield;
    this.workloadContractVersion = other.workloadContractVersion;
    this.boundedRange = other.boundedRange;
  }

  @Override
  public Capabilities deepCopy() {
    return new Capabilities(this);
  }

  @Override
  public void clear() {
    setWorkloadContractVersionIsSet(false);
    this.workloadContractVersion = 0;
    setBoundedRangeIsSet(false);
    this.boundedRange = false;
  }

  public int getWorkloadContractVersion() {
    return this.workloadContractVersion;
  }

  public Capabilities setWorkloadContractVersion(int workloadContractVersion) {
    this.workloadContractVersion = workloadContractVersion;
    setWorkloadContractVersionIsSet(true);
    return this;
  }

  public void unsetWorkloadContractVersion() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WORKLOADCONTRACTVERSION_ISSET_ID);
  }

  /** Returns true if field workloadContractVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetWorkloadContractVersion() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WORKLOADCONTRACTVERSION_ISSET_ID);
  }

  public void setWorkloadContractVersionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WORKLOADCONTRACTVERSION_ISSET_ID, value);
  }

  public boolean isBoundedRange() {
    return this.boundedRange;
  }

  public Capabilities setBoundedRange(boolean boundedRange) {
    this.boundedRange = boundedRange;
    setBoundedRangeIsSet(true);
    return this;
  }

  public void unsetBoundedRange() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BOUNDEDRANGE_ISSET_ID);
  }

  /** Returns true if field boundedRange is set (has been assigned a value) and false otherwise */
  public boolean isSetBoundedRange() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BOUNDEDRANGE_ISSET_ID);
  }

  public void setBoundedRangeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BOUNDEDRANGE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case WORKLOAD_CONTRACT_VERSION:
      if (value == null) {
        unsetWorkloadContractVersion();
      } else {
        setWorkloadContractVersion((java.lang.Integer)value);
      }
      break;

    case BOUNDED_RANGE:
      if (value == null) {
        unsetBoundedRange();
      } else {
        setBoundedRange((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case WORKLOAD_CONTRACT_VERSION:
      return getWorkloadContractVersion();

    case BOUNDED_RANGE:
      return isBoundedRange();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case WORKLOAD_CONTRACT_VERSION:
      return isSetWorkloadContractVersion();
    case BOUNDED_RANGE:
      return isSetBoundedRange();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Capabilities)
      return this.equals((Capabilities)that);
    return false;
  }

  public boolean equals(Capabilities that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_workloadContractVersion = true;
    boolean that_present_workloadContractVersion = true;
    if (this_present_workloadContractVersion || that_present_workloadContractVersion) {
      if (!(this_present_workloadContractVersion && that_present_workloadContractVersion))
        return false;
      if (this.workloadContractVersion != that.workloadContractVersion)
        return false;
    }

    boolean this_present_boundedRange = true;
    boolean that_present_boundedRange = true;
    if (this_present_boundedRange || that_present_boundedRange) {
      if (!(this_present_boundedRange && that_present_boundedRange))
        return false;
      if (this.boundedRange != that.boundedRange)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + workloadContractVersion;

    hashCode = hashCode * 8191 + ((boundedRange) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(Capabilities other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetWorkloadContractVersion(), other.isSetWorkloadContractVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWorkloadContractVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.workloadContractVersion, other.workloadContractVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBoundedRange(), other.isSetBoundedRange());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBoundedRange()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.boundedRange, other.boundedRange);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Capabilities(");
    boolean first = true;

    sb.append("workloadContractVersion:");
    sb.append(this.workloadContractVersion);
    first = false;
    if (!first) sb.append(", ");
    sb.append("boundedRange:");
    sb.append(this.boundedRange);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'workloadContractVersion' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'boundedRange' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CapabilitiesStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CapabilitiesStandardScheme getScheme() {
      return new CapabilitiesStandardScheme();
    }
  }

  private static class CapabilitiesStandardScheme extends org.apache.thrift.scheme.StandardScheme<Capabilities> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Capabilities struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // WORKLOAD_CONTRACT_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.workloadContractVersion = iprot.readI32();
              struct.setWorkloadContractVersionIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BOUNDED_RANGE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.boundedRange = iprot.readBool();
              struct.setBoundedRangeIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetWorkloadContractVersion()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'workloadContractVersion' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetBoundedRange()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'boundedRange' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Capabilities struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(WORKLOAD_CONTRACT_VERSION_FIELD_DESC);
      oprot.writeI32(struct.workloadContractVersion);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BOUNDED_RANGE_FIELD_DESC);
      oprot.writeBool(struct.boundedRange);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CapabilitiesTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CapabilitiesTupleScheme getScheme() {
      return new CapabilitiesTupleScheme();
    }
  }

  private static class CapabilitiesTupleScheme extends org.apache.thrift.scheme.TupleScheme<Capabilities> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Capabilities struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.workloadContractVersion);
      oprot.writeBool(struct.boundedRange);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Capabilities struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.workloadContractVersion = iprot.readI32();
      struct.setWorkloadContractVersionIsSet(true);
      struct.boundedRange = iprot.readBool();
      struct.setBoundedRangeIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
