/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class CdcCreateRequest implements org.apache.thrift.TBase<CdcCreateRequest, CdcCreateRequest._Fields>, java.io.Serializable, Cloneable, Comparable<CdcCreateRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CdcCreateRequest");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FROM_SEQ_FIELD_DESC = new org.apache.thrift.protocol.TField("fromSeq", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField COLUMN_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("columnIds", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField EMIT_LATEST_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("emitLatestValues", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField EXPECT_ABSENT_FIELD_DESC = new org.apache.thrift.protocol.TField("expectAbsent", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField EXPECTED_LAST_COMMITTED_SEQ_FIELD_DESC = new org.apache.thrift.protocol.TField("expectedLastCommittedSeq", org.apache.thrift.protocol.TType.I64, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CdcCreateRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CdcCreateRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String id; // required
  public long fromSeq; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> columnIds; // optional
  public boolean emitLatestValues; // optional
  public boolean expectAbsent; // optional
  public long expectedLastCommittedSeq; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    FROM_SEQ((short)2, "fromSeq"),
    COLUMN_IDS((short)3, "columnIds"),
    EMIT_LATEST_VALUES((short)4, "emitLatestValues"),
    EXPECT_ABSENT((short)5, "expectAbsent"),
    EXPECTED_LAST_COMMITTED_SEQ((short)6, "expectedLastCommittedSeq");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // FROM_SEQ
          return FROM_SEQ;
        case 3: // COLUMN_IDS
          return COLUMN_IDS;
        case 4: // EMIT_LATEST_VALUES
          return EMIT_LATEST_VALUES;
        case 5: // EXPECT_ABSENT
          return EXPECT_ABSENT;
        case 6: // EXPECTED_LAST_COMMITTED_SEQ
          return EXPECTED_LAST_COMMITTED_SEQ;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FROMSEQ_ISSET_ID = 0;
  private static final int __EMITLATESTVALUES_ISSET_ID = 1;
  private static final int __EXPECTABSENT_ISSET_ID = 2;
  private static final int __EXPECTEDLASTCOMMITTEDSEQ_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.FROM_SEQ,_Fields.COLUMN_IDS,_Fields.EMIT_LATEST_VALUES,_Fields.EXPECT_ABSENT,_Fields.EXPECTED_LAST_COMMITTED_SEQ};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FROM_SEQ, new org.apache.thrift.meta_data.FieldMetaData("fromSeq", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.COLUMN_IDS, new org.apache.thrift.meta_data.FieldMetaData("columnIds", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.EMIT_LATEST_VALUES, new org.apache.thrift.meta_data.FieldMetaData("emitLatestValues", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.EXPECT_ABSENT, new org.apache.thrift.meta_data.FieldMetaData("expectAbsent", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.EXPECTED_LAST_COMMITTED_SEQ, new org.apache.thrift.meta_data.FieldMetaData("expectedLastCommittedSeq", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CdcCreateRequest.class, metaDataMap);
  }

  public CdcCreateRequest() {
  }

  public CdcCreateRequest(
    java.lang.String id)
  {
    this();
    this.id = id;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CdcCreateRequest(CdcCreateRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetId()) {
      this.id = other.id;
    }
    this.fromSeq = other.fromSeq;
    if (other.isSetColumnIds()) {
      java.util.List<java.lang.Long> __this__columnIds = new java.util.ArrayList<java.lang.Long>(other.columnIds);
      this.columnIds = __this__columnIds;
    }
    this.emitLatestValues = other.emitLatestValues;
    this.expectAbsent = other.expectAbsent;
    this.expectedLastCommittedSeq = other.expectedLastCommittedSeq;
  }

  @Override
  public CdcCreateRequest deepCopy() {
    return new CdcCreateRequest(this);
  }

  @Override
  public void clear() {
    this.id = null;
    setFromSeqIsSet(false);
    this.fromSeq = 0;
    this.columnIds = null;
    setEmitLatestValuesIsSet(false);
    this.emitLatestValues = false;
    setExpectAbsentIsSet(false);
    this.expectAbsent = false;
    setExpectedLastCommittedSeqIsSet(false);
    this.expectedLastCommittedSeq = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getId() {
    return this.id;
  }

  public CdcCreateRequest setId(@org.apache.thrift.annotation.Nullable java.lang.String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public long getFromSeq() {
    return this.fromSeq;
  }

  public CdcCreateRequest setFromSeq(long fromSeq) {
    this.fromSeq = fromSeq;
    setFromSeqIsSet(true);
    return this;
  }

  public void unsetFromSeq() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FROMSEQ_ISSET_ID);
  }

  /** Returns true if field fromSeq is set (has been assigned a value) and false otherwise */
  public boolean isSetFromSeq() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FROMSEQ_ISSET_ID);
  }

  public void setFromSeqIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FROMSEQ_ISSET_ID, value);
  }

  public int getColumnIdsSize() {
    return (this.columnIds == null) ? 0 : this.columnIds.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Long> getColumnIdsIterator() {
    return (this.columnIds == null) ? null : this.columnIds.iterator();
  }

  public void addToColumnIds(long elem) {
    if (this.columnIds == null) {
      this.columnIds = new java.util.ArrayList<java.lang.Long>();
    }
    this.columnIds.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Long> getColumnIds() {
    return this.columnIds;
  }

  public CdcCreateRequest setColumnIds(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Long> columnIds) {
    this.columnIds = columnIds;
    return this;
  }

  public void unsetColumnIds() {
    this.columnIds = null;
  }

  /** Returns true if field columnIds is set (has been assigned a value) and false otherwise */
  public boolean isSetColumnIds() {
    return this.columnIds != null;
  }

  public void setColumnIdsIsSet(boolean value) {
    if (!value) {
      this.columnIds = null;
    }
  }

  public boolean isEmitLatestValues() {
    return this.emitLatestValues;
  }

  public CdcCreateRequest setEmitLatestValues(boolean emitLatestValues) {
    this.emitLatestValues = emitLatestValues;
    setEmitLatestValuesIsSet(true);
    return this;
  }

  public void unsetEmitLatestValues() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EMITLATESTVALUES_ISSET_ID);
  }

  /** Returns true if field emitLatestValues is set (has been assigned a value) and false otherwise */
  public boolean isSetEmitLatestValues() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EMITLATESTVALUES_ISSET_ID);
  }

  public void setEmitLatestValuesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EMITLATESTVALUES_ISSET_ID, value);
  }

  public boolean isExpectAbsent() {
    return this.expectAbsent;
  }

  public CdcCreateRequest setExpectAbsent(boolean expectAbsent) {
    this.expectAbsent = expectAbsent;
    setExpectAbsentIsSet(true);
    return this;
  }

  public void unsetExpectAbsent() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXPECTABSENT_ISSET_ID);
  }

  /** Returns true if field expectAbsent is set (has been assigned a value) and false otherwise */
  public boolean isSetExpectAbsent() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXPECTABSENT_ISSET_ID);
  }

  public void setExpectAbsentIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXPECTABSENT_ISSET_ID, value);
  }

  public long getExpectedLastCommittedSeq() {
    return this.expectedLastCommittedSeq;
  }

  public CdcCreateRequest setExpectedLastCommittedSeq(long expectedLastCommittedSeq) {
    this.expectedLastCommittedSeq = expectedLastCommittedSeq;
    setExpectedLastCommittedSeqIsSet(true);
    return this;
  }

  public void unsetExpectedLastCommittedSeq() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXPECTEDLASTCOMMITTEDSEQ_ISSET_ID);
  }

  /** Returns true if field expectedLastCommittedSeq is set (has been assigned a value) and false otherwise */
  public boolean isSetExpectedLastCommittedSeq() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXPECTEDLASTCOMMITTEDSEQ_ISSET_ID);
  }

  public void setExpectedLastCommittedSeqIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXPECTEDLASTCOMMITTEDSEQ_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.String)value);
      }
      break;

    case FROM_SEQ:
      if (value == null) {
        unsetFromSeq();
      } else {
        setFromSeq((java.lang.Long)value);
      }
      break;

    case COLUMN_IDS:
      if (value == null) {
        unsetColumnIds();
      } else {
        setColumnIds((java.util.List<java.lang.Long>)value);
      }
      break;

    case EMIT_LATEST_VALUES:
      if (value == null) {
        unsetEmitLatestValues();
      } else {
        setEmitLatestValues((java.lang.Boolean)value);
      }
      break;

    case EXPECT_ABSENT:
      if (value == null) {
        unsetExpectAbsent();
      } else {
        setExpectAbsent((java.lang.Boolean)value);
      }
      break;

    case EXPECTED_LAST_COMMITTED_SEQ:
      if (value == null) {
        unsetExpectedLastCommittedSeq();
      } else {
        setExpectedLastCommittedSeq((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case FROM_SEQ:
      return getFromSeq();

    case COLUMN_IDS:
      return getColumnIds();

    case EMIT_LATEST_VALUES:
      return isEmitLatestValues();

    case EXPECT_ABSENT:
      return isExpectAbsent();

    case EXPECTED_LAST_COMMITTED_SEQ:
      return getExpectedLastCommittedSeq();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case FROM_SEQ:
      return isSetFromSeq();
    case COLUMN_IDS:
      return isSetColumnIds();
    case EMIT_LATEST_VALUES:
      return isSetEmitLatestValues();
    case EXPECT_ABSENT:
      return isSetExpectAbsent();
    case EXPECTED_LAST_COMMITTED_SEQ:
      return isSetExpectedLastCommittedSeq();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof CdcCreateRequest)
      return this.equals((CdcCreateRequest)that);
    return false;
  }

  public boolean equals(CdcCreateRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_fromSeq = true && this.isSetFromSeq();
    boolean that_present_fromSeq = true && that.isSetFromSeq();
    if (this_present_fromSeq || that_present_fromSeq) {
      if (!(this_present_fromSeq && that_present_fromSeq))
        return false;
      if (this.fromSeq != that.fromSeq)
        return false;
    }

    boolean this_present_columnIds = true && this.isSetColumnIds();
    boolean that_present_columnIds = true && that.isSetColumnIds();
    if (this_present_columnIds || that_present_columnIds) {
      if (!(this_present_columnIds && that_present_columnIds))
        return false;
      if (!this.columnIds.equals(that.columnIds))
        return false;
    }

    boolean this_present_emitLatestValues = true && this.isSetEmitLatestValues();
    boolean that_present_emitLatestValues = true && that.isSetEmitLatestValues();
    if (this_present_emitLatestValues || that_present_emitLatestValues) {
      if (!(this_present_emitLatestValues && that_present_emitLatestValues))
        return false;
      if (this.emitLatestValues != that.emitLatestValues)
        return false;
    }

    boolean this_present_expectAbsent = true && this.isSetExpectAbsent();
    boolean that_present_expectAbsent = true && that.isSetExpectAbsent();
    if (this_present_expectAbsent || that_present_expectAbsent) {
      if (!(this_present_expectAbsent && that_present_expectAbsent))
        return false;
      if (this.expectAbsent != that.expectAbsent)
        return false;
    }

    boolean this_present_expectedLastCommittedSeq = true && this.isSetExpectedLastCommittedSeq();
    boolean that_present_expectedLastCommittedSeq = true && that.isSetExpectedLastCommittedSeq();
    if (this_present_expectedLastCommittedSeq || that_present_expectedLastCommittedSeq) {
      if (!(this_present_expectedLastCommittedSeq && that_present_expectedLastCommittedSeq))
        return false;
      if (this.expectedLastCommittedSeq != that.expectedLastCommittedSeq)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId()) ? 131071 : 524287);
    if (isSetId())
      hashCode = hashCode * 8191 + id.hashCode();

    hashCode = hashCode * 8191 + ((isSetFromSeq()) ? 131071 : 524287);
    if (isSetFromSeq())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(fromSeq);

    hashCode = hashCode * 8191 + ((isSetColumnIds()) ? 131071 : 524287);
    if (isSetColumnIds())
      hashCode = hashCode * 8191 + columnIds.hashCode();

    hashCode = hashCode * 8191 + ((isSetEmitLatestValues()) ? 131071 : 524287);
    if (isSetEmitLatestValues())
      hashCode = hashCode * 8191 + ((emitLatestValues) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetExpectAbsent()) ? 131071 : 524287);
    if (isSetExpectAbsent())
      hashCode = hashCode * 8191 + ((expectAbsent) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetExpectedLastCommittedSeq()) ? 131071 : 524287);
    if (isSetExpectedLastCommittedSeq())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(expectedLastCommittedSeq);

    return hashCode;
  }

  @Override
  public int compareTo(CdcCreateRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFromSeq(), other.isSetFromSeq());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFromSeq()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fromSeq, other.fromSeq);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetColumnIds(), other.isSetColumnIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumnIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.columnIds, other.columnIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEmitLatestValues(), other.isSetEmitLatestValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmitLatestValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.emitLatestValues, other.emitLatestValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetExpectAbsent(), other.isSetExpectAbsent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpectAbsent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expectAbsent, other.expectAbsent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetExpectedLastCommittedSeq(), other.isSetExpectedLastCommittedSeq());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpectedLastCommittedSeq()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expectedLastCommittedSeq, other.expectedLastCommittedSeq);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CdcCreateRequest(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (isSetFromSeq()) {
      if (!first) sb.append(", ");
      sb.append("fromSeq:");
      sb.append(this.fromSeq);
      first = false;
    }
    if (isSetColumnIds()) {
      if (!first) sb.append(", ");
      sb.append("columnIds:");
      if (this.columnIds == null) {
        sb.append("null");
      } else {
        sb.append(this.columnIds);
      }
      first = false;
    }
    if (isSetEmitLatestValues()) {
      if (!first) sb.append(", ");
      sb.append("emitLatestValues:");
      sb.append(this.emitLatestValues);
      first = false;
    }
    if (isSetExpectAbsent()) {
      if (!first) sb.append(", ");
      sb.append("expectAbsent:");
      sb.append(this.expectAbsent);
      first = false;
    }
    if (isSetExpectedLastCommittedSeq()) {
      if (!first) sb.append(", ");
      sb.append("expectedLastCommittedSeq:");
      sb.append(this.expectedLastCommittedSeq);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CdcCreateRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CdcCreateRequestStandardScheme getScheme() {
      return new CdcCreateRequestStandardScheme();
    }
  }

  private static class CdcCreateRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<CdcCreateRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, CdcCreateRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FROM_SEQ
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.fromSeq = iprot.readI64();
              struct.setFromSeqIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COLUMN_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.columnIds = new java.util.ArrayList<java.lang.Long>(_list24.size);
                long _elem25;
                for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                {
                  _elem25 = iprot.readI64();
                  struct.columnIds.add(_elem25);
                }
                iprot.readListEnd();
              }
              struct.setColumnIdsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // EMIT_LATEST_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.emitLatestValues = iprot.readBool();
              struct.setEmitLatestValuesIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // EXPECT_ABSENT
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.expectAbsent = iprot.readBool();
              struct.setExpectAbsentIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // EXPECTED_LAST_COMMITTED_SEQ
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.expectedLastCommittedSeq = iprot.readI64();
              struct.setExpectedLastCommittedSeqIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, CdcCreateRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetFromSeq()) {
        oprot.writeFieldBegin(FROM_SEQ_FIELD_DESC);
        oprot.writeI64(struct.fromSeq);
        oprot.writeFieldEnd();
      }
      if (struct.columnIds != null) {
        if (struct.isSetColumnIds()) {
          oprot.writeFieldBegin(COLUMN_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.columnIds.size()));
            for (long _iter27 : struct.columnIds)
            {
              oprot.writeI64(_iter27);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetEmitLatestValues()) {
        oprot.writeFieldBegin(EMIT_LATEST_VALUES_FIELD_DESC);
        oprot.writeBool(struct.emitLatestValues);
        oprot.writeFieldEnd();
      }
      if (struct.isSetExpectAbsent()) {
        oprot.writeFieldBegin(EXPECT_ABSENT_FIELD_DESC);
        oprot.writeBool(struct.expectAbsent);
        oprot.writeFieldEnd();
      }
      if (struct.isSetExpectedLastCommittedSeq()) {
        oprot.writeFieldBegin(EXPECTED_LAST_COMMITTED_SEQ_FIELD_DESC);
        oprot.writeI64(struct.expectedLastCommittedSeq);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CdcCreateRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CdcCreateRequestTupleScheme getScheme() {
      return new CdcCreateRequestTupleScheme();
    }
  }

  private static class CdcCreateRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<CdcCreateRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CdcCreateRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.id);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFromSeq()) {
        optionals.set(0);
      }
      if (struct.isSetColumnIds()) {
        optionals.set(1);
      }
      if (struct.isSetEmitLatestValues()) {
        optionals.set(2);
      }
      if (struct.isSetExpectAbsent()) {
        optionals.set(3);
      }
      if (struct.isSetExpectedLastCommittedSeq()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetFromSeq()) {
        oprot.writeI64(struct.fromSeq);
      }
      if (struct.isSetColumnIds()) {
        {
          oprot.writeI32(struct.columnIds.size());
          for (long _iter28 : struct.columnIds)
          {
            oprot.writeI64(_iter28);
          }
        }
      }
      if (struct.isSetEmitLatestValues()) {
        oprot.writeBool(struct.emitLatestValues);
      }
      if (struct.isSetExpectAbsent()) {
        oprot.writeBool(struct.expectAbsent);
      }
      if (struct.isSetExpectedLastCommittedSeq()) {
        oprot.writeI64(struct.expectedLastCommittedSeq);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CdcCreateRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.id = iprot.readString();
      struct.setIdIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.fromSeq = iprot.readI64();
        struct.setFromSeqIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list29 = iprot.readListBegin(org.apache.thrift.protocol.TType.I64);
          struct.columnIds = new java.util.ArrayList<java.lang.Long>(_list29.size);
          long _elem30;
          for (int _i31 = 0; _i31 < _list29.size; ++_i31)
          {
            _elem30 = iprot.readI64();
            struct.columnIds.add(_elem30);
          }
        }
        struct.setColumnIdsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.emitLatestValues = iprot.readBool();
        struct.setEmitLatestValuesIsSet(true);
      }
      if (incoming.get(3)) {
        struct.expectAbsent = iprot.readBool();
        struct.setExpectAbsentIsSet(true);
      }
      if (incoming.get(4)) {
        struct.expectedLastCommittedSeq = iprot.readI64();
        struct.setExpectedLastCommittedSeqIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
