/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum CDCOperation implements org.apache.thrift.TEnum {
  PUT(0),
  DELETE(1),
  MERGE(2);

  private final int value;

  private CDCOperation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static CDCOperation findByValue(int value) {
    switch (value) {
      case 0:
        return PUT;
      case 1:
        return DELETE;
      case 2:
        return MERGE;
      default:
        return null;
    }
  }
}
