/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class CdcPollRequest implements org.apache.thrift.TBase<CdcPollRequest, CdcPollRequest._Fields>, java.io.Serializable, Cloneable, Comparable<CdcPollRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CdcPollRequest");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FROM_SEQ_FIELD_DESC = new org.apache.thrift.protocol.TField("fromSeq", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField MAX_EVENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("maxEvents", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField MAX_RESPONSE_BYTES_FIELD_DESC = new org.apache.thrift.protocol.TField("maxResponseBytes", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CdcPollRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CdcPollRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String id; // required
  public long fromSeq; // optional
  public long maxEvents; // required
  public int maxResponseBytes; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    FROM_SEQ((short)2, "fromSeq"),
    MAX_EVENTS((short)3, "maxEvents"),
    MAX_RESPONSE_BYTES((short)4, "maxResponseBytes");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // FROM_SEQ
          return FROM_SEQ;
        case 3: // MAX_EVENTS
          return MAX_EVENTS;
        case 4: // MAX_RESPONSE_BYTES
          return MAX_RESPONSE_BYTES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FROMSEQ_ISSET_ID = 0;
  private static final int __MAXEVENTS_ISSET_ID = 1;
  private static final int __MAXRESPONSEBYTES_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.FROM_SEQ,_Fields.MAX_RESPONSE_BYTES};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FROM_SEQ, new org.apache.thrift.meta_data.FieldMetaData("fromSeq", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.MAX_EVENTS, new org.apache.thrift.meta_data.FieldMetaData("maxEvents", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.MAX_RESPONSE_BYTES, new org.apache.thrift.meta_data.FieldMetaData("maxResponseBytes", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CdcPollRequest.class, metaDataMap);
  }

  public CdcPollRequest() {
  }

  public CdcPollRequest(
    java.lang.String id,
    long maxEvents)
  {
    this();
    this.id = id;
    this.maxEvents = maxEvents;
    setMaxEventsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CdcPollRequest(CdcPollRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetId()) {
      this.id = other.id;
    }
    this.fromSeq = other.fromSeq;
    this.maxEvents = other.maxEvents;
    this.maxResponseBytes = other.maxResponseBytes;
  }

  @Override
  public CdcPollRequest deepCopy() {
    return new CdcPollRequest(this);
  }

  @Override
  public void clear() {
    this.id = null;
    setFromSeqIsSet(false);
    this.fromSeq = 0;
    setMaxEventsIsSet(false);
    this.maxEvents = 0;
    setMaxResponseBytesIsSet(false);
    this.maxResponseBytes = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getId() {
    return this.id;
  }

  public CdcPollRequest setId(@org.apache.thrift.annotation.Nullable java.lang.String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public long getFromSeq() {
    return this.fromSeq;
  }

  public CdcPollRequest setFromSeq(long fromSeq) {
    this.fromSeq = fromSeq;
    setFromSeqIsSet(true);
    return this;
  }

  public void unsetFromSeq() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FROMSEQ_ISSET_ID);
  }

  /** Returns true if field fromSeq is set (has been assigned a value) and false otherwise */
  public boolean isSetFromSeq() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FROMSEQ_ISSET_ID);
  }

  public void setFromSeqIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FROMSEQ_ISSET_ID, value);
  }

  public long getMaxEvents() {
    return this.maxEvents;
  }

  public CdcPollRequest setMaxEvents(long maxEvents) {
    this.maxEvents = maxEvents;
    setMaxEventsIsSet(true);
    return this;
  }

  public void unsetMaxEvents() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXEVENTS_ISSET_ID);
  }

  /** Returns true if field maxEvents is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxEvents() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXEVENTS_ISSET_ID);
  }

  public void setMaxEventsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXEVENTS_ISSET_ID, value);
  }

  public int getMaxResponseBytes() {
    return this.maxResponseBytes;
  }

  public CdcPollRequest setMaxResponseBytes(int maxResponseBytes) {
    this.maxResponseBytes = maxResponseBytes;
    setMaxResponseBytesIsSet(true);
    return this;
  }

  public void unsetMaxResponseBytes() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXRESPONSEBYTES_ISSET_ID);
  }

  /** Returns true if field maxResponseBytes is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxResponseBytes() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXRESPONSEBYTES_ISSET_ID);
  }

  public void setMaxResponseBytesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXRESPONSEBYTES_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.String)value);
      }
      break;

    case FROM_SEQ:
      if (value == null) {
        unsetFromSeq();
      } else {
        setFromSeq((java.lang.Long)value);
      }
      break;

    case MAX_EVENTS:
      if (value == null) {
        unsetMaxEvents();
      } else {
        setMaxEvents((java.lang.Long)value);
      }
      break;

    case MAX_RESPONSE_BYTES:
      if (value == null) {
        unsetMaxResponseBytes();
      } else {
        setMaxResponseBytes((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case FROM_SEQ:
      return getFromSeq();

    case MAX_EVENTS:
      return getMaxEvents();

    case MAX_RESPONSE_BYTES:
      return getMaxResponseBytes();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case FROM_SEQ:
      return isSetFromSeq();
    case MAX_EVENTS:
      return isSetMaxEvents();
    case MAX_RESPONSE_BYTES:
      return isSetMaxResponseBytes();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof CdcPollRequest)
      return this.equals((CdcPollRequest)that);
    return false;
  }

  public boolean equals(CdcPollRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_fromSeq = true && this.isSetFromSeq();
    boolean that_present_fromSeq = true && that.isSetFromSeq();
    if (this_present_fromSeq || that_present_fromSeq) {
      if (!(this_present_fromSeq && that_present_fromSeq))
        return false;
      if (this.fromSeq != that.fromSeq)
        return false;
    }

    boolean this_present_maxEvents = true;
    boolean that_present_maxEvents = true;
    if (this_present_maxEvents || that_present_maxEvents) {
      if (!(this_present_maxEvents && that_present_maxEvents))
        return false;
      if (this.maxEvents != that.maxEvents)
        return false;
    }

    boolean this_present_maxResponseBytes = true && this.isSetMaxResponseBytes();
    boolean that_present_maxResponseBytes = true && that.isSetMaxResponseBytes();
    if (this_present_maxResponseBytes || that_present_maxResponseBytes) {
      if (!(this_present_maxResponseBytes && that_present_maxResponseBytes))
        return false;
      if (this.maxResponseBytes != that.maxResponseBytes)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId()) ? 131071 : 524287);
    if (isSetId())
      hashCode = hashCode * 8191 + id.hashCode();

    hashCode = hashCode * 8191 + ((isSetFromSeq()) ? 131071 : 524287);
    if (isSetFromSeq())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(fromSeq);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(maxEvents);

    hashCode = hashCode * 8191 + ((isSetMaxResponseBytes()) ? 131071 : 524287);
    if (isSetMaxResponseBytes())
      hashCode = hashCode * 8191 + maxResponseBytes;

    return hashCode;
  }

  @Override
  public int compareTo(CdcPollRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFromSeq(), other.isSetFromSeq());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFromSeq()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fromSeq, other.fromSeq);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMaxEvents(), other.isSetMaxEvents());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxEvents()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxEvents, other.maxEvents);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMaxResponseBytes(), other.isSetMaxResponseBytes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxResponseBytes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxResponseBytes, other.maxResponseBytes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CdcPollRequest(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (isSetFromSeq()) {
      if (!first) sb.append(", ");
      sb.append("fromSeq:");
      sb.append(this.fromSeq);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("maxEvents:");
    sb.append(this.maxEvents);
    first = false;
    if (isSetMaxResponseBytes()) {
      if (!first) sb.append(", ");
      sb.append("maxResponseBytes:");
      sb.append(this.maxResponseBytes);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'maxEvents' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CdcPollRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CdcPollRequestStandardScheme getScheme() {
      return new CdcPollRequestStandardScheme();
    }
  }

  private static class CdcPollRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<CdcPollRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, CdcPollRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FROM_SEQ
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.fromSeq = iprot.readI64();
              struct.setFromSeqIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MAX_EVENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.maxEvents = iprot.readI64();
              struct.setMaxEventsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // MAX_RESPONSE_BYTES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxResponseBytes = iprot.readI32();
              struct.setMaxResponseBytesIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetMaxEvents()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxEvents' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, CdcPollRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetFromSeq()) {
        oprot.writeFieldBegin(FROM_SEQ_FIELD_DESC);
        oprot.writeI64(struct.fromSeq);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MAX_EVENTS_FIELD_DESC);
      oprot.writeI64(struct.maxEvents);
      oprot.writeFieldEnd();
      if (struct.isSetMaxResponseBytes()) {
        oprot.writeFieldBegin(MAX_RESPONSE_BYTES_FIELD_DESC);
        oprot.writeI32(struct.maxResponseBytes);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CdcPollRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CdcPollRequestTupleScheme getScheme() {
      return new CdcPollRequestTupleScheme();
    }
  }

  private static class CdcPollRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<CdcPollRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CdcPollRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.id);
      oprot.writeI64(struct.maxEvents);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFromSeq()) {
        optionals.set(0);
      }
      if (struct.isSetMaxResponseBytes()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetFromSeq()) {
        oprot.writeI64(struct.fromSeq);
      }
      if (struct.isSetMaxResponseBytes()) {
        oprot.writeI32(struct.maxResponseBytes);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CdcPollRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.id = iprot.readString();
      struct.setIdIsSet(true);
      struct.maxEvents = iprot.readI64();
      struct.setMaxEventsIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.fromSeq = iprot.readI64();
        struct.setFromSeqIsSet(true);
      }
      if (incoming.get(1)) {
        struct.maxResponseBytes = iprot.readI32();
        struct.setMaxResponseBytesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
