/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class CdcPollBatchResult implements org.apache.thrift.TBase<CdcPollBatchResult, CdcPollBatchResult._Fields>, java.io.Serializable, Cloneable, Comparable<CdcPollBatchResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CdcPollBatchResult");

  private static final org.apache.thrift.protocol.TField EVENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("events", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField NEXT_SEQ_FIELD_DESC = new org.apache.thrift.protocol.TField("nextSeq", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CdcPollBatchResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CdcPollBatchResultTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<CDCEvent> events; // required
  public long nextSeq; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EVENTS((short)1, "events"),
    NEXT_SEQ((short)2, "nextSeq");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EVENTS
          return EVENTS;
        case 2: // NEXT_SEQ
          return NEXT_SEQ;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NEXTSEQ_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EVENTS, new org.apache.thrift.meta_data.FieldMetaData("events", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CDCEvent.class))));
    tmpMap.put(_Fields.NEXT_SEQ, new org.apache.thrift.meta_data.FieldMetaData("nextSeq", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CdcPollBatchResult.class, metaDataMap);
  }

  public CdcPollBatchResult() {
  }

  public CdcPollBatchResult(
    java.util.List<CDCEvent> events,
    long nextSeq)
  {
    this();
    this.events = events;
    this.nextSeq = nextSeq;
    setNextSeqIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CdcPollBatchResult(CdcPollBatchResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetEvents()) {
      java.util.List<CDCEvent> __this__events = new java.util.ArrayList<CDCEvent>(other.events.size());
      for (CDCEvent other_element : other.events) {
        __this__events.add(new CDCEvent(other_element));
      }
      this.events = __this__events;
    }
    this.nextSeq = other.nextSeq;
  }

  @Override
  public CdcPollBatchResult deepCopy() {
    return new CdcPollBatchResult(this);
  }

  @Override
  public void clear() {
    this.events = null;
    setNextSeqIsSet(false);
    this.nextSeq = 0;
  }

  public int getEventsSize() {
    return (this.events == null) ? 0 : this.events.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<CDCEvent> getEventsIterator() {
    return (this.events == null) ? null : this.events.iterator();
  }

  public void addToEvents(CDCEvent elem) {
    if (this.events == null) {
      this.events = new java.util.ArrayList<CDCEvent>();
    }
    this.events.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<CDCEvent> getEvents() {
    return this.events;
  }

  public CdcPollBatchResult setEvents(@org.apache.thrift.annotation.Nullable java.util.List<CDCEvent> events) {
    this.events = events;
    return this;
  }

  public void unsetEvents() {
    this.events = null;
  }

  /** Returns true if field events is set (has been assigned a value) and false otherwise */
  public boolean isSetEvents() {
    return this.events != null;
  }

  public void setEventsIsSet(boolean value) {
    if (!value) {
      this.events = null;
    }
  }

  public long getNextSeq() {
    return this.nextSeq;
  }

  public CdcPollBatchResult setNextSeq(long nextSeq) {
    this.nextSeq = nextSeq;
    setNextSeqIsSet(true);
    return this;
  }

  public void unsetNextSeq() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NEXTSEQ_ISSET_ID);
  }

  /** Returns true if field nextSeq is set (has been assigned a value) and false otherwise */
  public boolean isSetNextSeq() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NEXTSEQ_ISSET_ID);
  }

  public void setNextSeqIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NEXTSEQ_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case EVENTS:
      if (value == null) {
        unsetEvents();
      } else {
        setEvents((java.util.List<CDCEvent>)value);
      }
      break;

    case NEXT_SEQ:
      if (value == null) {
        unsetNextSeq();
      } else {
        setNextSeq((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EVENTS:
      return getEvents();

    case NEXT_SEQ:
      return getNextSeq();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EVENTS:
      return isSetEvents();
    case NEXT_SEQ:
      return isSetNextSeq();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof CdcPollBatchResult)
      return this.equals((CdcPollBatchResult)that);
    return false;
  }

  public boolean equals(CdcPollBatchResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_events = true && this.isSetEvents();
    boolean that_present_events = true && that.isSetEvents();
    if (this_present_events || that_present_events) {
      if (!(this_present_events && that_present_events))
        return false;
      if (!this.events.equals(that.events))
        return false;
    }

    boolean this_present_nextSeq = true;
    boolean that_present_nextSeq = true;
    if (this_present_nextSeq || that_present_nextSeq) {
      if (!(this_present_nextSeq && that_present_nextSeq))
        return false;
      if (this.nextSeq != that.nextSeq)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetEvents()) ? 131071 : 524287);
    if (isSetEvents())
      hashCode = hashCode * 8191 + events.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(nextSeq);

    return hashCode;
  }

  @Override
  public int compareTo(CdcPollBatchResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetEvents(), other.isSetEvents());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEvents()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.events, other.events);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNextSeq(), other.isSetNextSeq());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNextSeq()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nextSeq, other.nextSeq);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CdcPollBatchResult(");
    boolean first = true;

    sb.append("events:");
    if (this.events == null) {
      sb.append("null");
    } else {
      sb.append(this.events);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nextSeq:");
    sb.append(this.nextSeq);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (events == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'events' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'nextSeq' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CdcPollBatchResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CdcPollBatchResultStandardScheme getScheme() {
      return new CdcPollBatchResultStandardScheme();
    }
  }

  private static class CdcPollBatchResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<CdcPollBatchResult> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, CdcPollBatchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // EVENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.events = new java.util.ArrayList<CDCEvent>(_list16.size);
                @org.apache.thrift.annotation.Nullable CDCEvent _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = new CDCEvent();
                  _elem17.read(iprot);
                  struct.events.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setEventsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NEXT_SEQ
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.nextSeq = iprot.readI64();
              struct.setNextSeqIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetNextSeq()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'nextSeq' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, CdcPollBatchResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.events != null) {
        oprot.writeFieldBegin(EVENTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.events.size()));
          for (CDCEvent _iter19 : struct.events)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NEXT_SEQ_FIELD_DESC);
      oprot.writeI64(struct.nextSeq);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CdcPollBatchResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public CdcPollBatchResultTupleScheme getScheme() {
      return new CdcPollBatchResultTupleScheme();
    }
  }

  private static class CdcPollBatchResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<CdcPollBatchResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CdcPollBatchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        oprot.writeI32(struct.events.size());
        for (CDCEvent _iter20 : struct.events)
        {
          _iter20.write(oprot);
        }
      }
      oprot.writeI64(struct.nextSeq);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CdcPollBatchResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list21 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
        struct.events = new java.util.ArrayList<CDCEvent>(_list21.size);
        @org.apache.thrift.annotation.Nullable CDCEvent _elem22;
        for (int _i23 = 0; _i23 < _list21.size; ++_i23)
        {
          _elem22 = new CDCEvent();
          _elem22.read(iprot);
          struct.events.add(_elem22);
        }
      }
      struct.setEventsIsSet(true);
      struct.nextSeq = iprot.readI64();
      struct.setNextSeqIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
