/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Delta implements org.apache.thrift.TBase<Delta, Delta._Fields>, java.io.Serializable, Cloneable, Comparable<Delta> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Delta");

  private static final org.apache.thrift.protocol.TField PREVIOUS_FIELD_DESC = new org.apache.thrift.protocol.TField("previous", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CURRENT_FIELD_DESC = new org.apache.thrift.protocol.TField("current", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DeltaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DeltaTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer previous; // optional
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer current; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PREVIOUS((short)1, "previous"),
    CURRENT((short)2, "current");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PREVIOUS
          return PREVIOUS;
        case 2: // CURRENT
          return CURRENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields[] optionals = {_Fields.PREVIOUS,_Fields.CURRENT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PREVIOUS, new org.apache.thrift.meta_data.FieldMetaData("previous", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.CURRENT, new org.apache.thrift.meta_data.FieldMetaData("current", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Delta.class, metaDataMap);
  }

  public Delta() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Delta(Delta other) {
    if (other.isSetPrevious()) {
      this.previous = org.apache.thrift.TBaseHelper.copyBinary(other.previous);
    }
    if (other.isSetCurrent()) {
      this.current = org.apache.thrift.TBaseHelper.copyBinary(other.current);
    }
  }

  @Override
  public Delta deepCopy() {
    return new Delta(this);
  }

  @Override
  public void clear() {
    this.previous = null;
    this.current = null;
  }

  public byte[] getPrevious() {
    setPrevious(org.apache.thrift.TBaseHelper.rightSize(previous));
    return previous == null ? null : previous.array();
  }

  public java.nio.ByteBuffer bufferForPrevious() {
    return org.apache.thrift.TBaseHelper.copyBinary(previous);
  }

  public Delta setPrevious(byte[] previous) {
    this.previous = previous == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(previous.clone());
    return this;
  }

  public Delta setPrevious(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer previous) {
    this.previous = org.apache.thrift.TBaseHelper.copyBinary(previous);
    return this;
  }

  public void unsetPrevious() {
    this.previous = null;
  }

  /** Returns true if field previous is set (has been assigned a value) and false otherwise */
  public boolean isSetPrevious() {
    return this.previous != null;
  }

  public void setPreviousIsSet(boolean value) {
    if (!value) {
      this.previous = null;
    }
  }

  public byte[] getCurrent() {
    setCurrent(org.apache.thrift.TBaseHelper.rightSize(current));
    return current == null ? null : current.array();
  }

  public java.nio.ByteBuffer bufferForCurrent() {
    return org.apache.thrift.TBaseHelper.copyBinary(current);
  }

  public Delta setCurrent(byte[] current) {
    this.current = current == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(current.clone());
    return this;
  }

  public Delta setCurrent(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer current) {
    this.current = org.apache.thrift.TBaseHelper.copyBinary(current);
    return this;
  }

  public void unsetCurrent() {
    this.current = null;
  }

  /** Returns true if field current is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrent() {
    return this.current != null;
  }

  public void setCurrentIsSet(boolean value) {
    if (!value) {
      this.current = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PREVIOUS:
      if (value == null) {
        unsetPrevious();
      } else {
        if (value instanceof byte[]) {
          setPrevious((byte[])value);
        } else {
          setPrevious((java.nio.ByteBuffer)value);
        }
      }
      break;

    case CURRENT:
      if (value == null) {
        unsetCurrent();
      } else {
        if (value instanceof byte[]) {
          setCurrent((byte[])value);
        } else {
          setCurrent((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PREVIOUS:
      return getPrevious();

    case CURRENT:
      return getCurrent();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PREVIOUS:
      return isSetPrevious();
    case CURRENT:
      return isSetCurrent();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Delta)
      return this.equals((Delta)that);
    return false;
  }

  public boolean equals(Delta that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_previous = true && this.isSetPrevious();
    boolean that_present_previous = true && that.isSetPrevious();
    if (this_present_previous || that_present_previous) {
      if (!(this_present_previous && that_present_previous))
        return false;
      if (!this.previous.equals(that.previous))
        return false;
    }

    boolean this_present_current = true && this.isSetCurrent();
    boolean that_present_current = true && that.isSetCurrent();
    if (this_present_current || that_present_current) {
      if (!(this_present_current && that_present_current))
        return false;
      if (!this.current.equals(that.current))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPrevious()) ? 131071 : 524287);
    if (isSetPrevious())
      hashCode = hashCode * 8191 + previous.hashCode();

    hashCode = hashCode * 8191 + ((isSetCurrent()) ? 131071 : 524287);
    if (isSetCurrent())
      hashCode = hashCode * 8191 + current.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Delta other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPrevious(), other.isSetPrevious());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrevious()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.previous, other.previous);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCurrent(), other.isSetCurrent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.current, other.current);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Delta(");
    boolean first = true;

    if (isSetPrevious()) {
      sb.append("previous:");
      if (this.previous == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.previous, sb);
      }
      first = false;
    }
    if (isSetCurrent()) {
      if (!first) sb.append(", ");
      sb.append("current:");
      if (this.current == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.current, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DeltaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DeltaStandardScheme getScheme() {
      return new DeltaStandardScheme();
    }
  }

  private static class DeltaStandardScheme extends org.apache.thrift.scheme.StandardScheme<Delta> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Delta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PREVIOUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.previous = iprot.readBinary();
              struct.setPreviousIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CURRENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.current = iprot.readBinary();
              struct.setCurrentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Delta struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.previous != null) {
        if (struct.isSetPrevious()) {
          oprot.writeFieldBegin(PREVIOUS_FIELD_DESC);
          oprot.writeBinary(struct.previous);
          oprot.writeFieldEnd();
        }
      }
      if (struct.current != null) {
        if (struct.isSetCurrent()) {
          oprot.writeFieldBegin(CURRENT_FIELD_DESC);
          oprot.writeBinary(struct.current);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DeltaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DeltaTupleScheme getScheme() {
      return new DeltaTupleScheme();
    }
  }

  private static class DeltaTupleScheme extends org.apache.thrift.scheme.TupleScheme<Delta> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Delta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPrevious()) {
        optionals.set(0);
      }
      if (struct.isSetCurrent()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPrevious()) {
        oprot.writeBinary(struct.previous);
      }
      if (struct.isSetCurrent()) {
        oprot.writeBinary(struct.current);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Delta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.previous = iprot.readBinary();
        struct.setPreviousIsSet(true);
      }
      if (incoming.get(1)) {
        struct.current = iprot.readBinary();
        struct.setCurrentIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

