/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum MergeBatchMode implements org.apache.thrift.TEnum {
  MERGE_WRITE_BATCH(0),
  MERGE_WRITE_BATCH_NO_WAL(1),
  MERGE_SST_INGESTION(2),
  MERGE_SST_INGEST_BEHIND(3);

  private final int value;

  private MergeBatchMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static MergeBatchMode findByValue(int value) { 
    switch (value) {
      case 0:
        return MERGE_WRITE_BATCH;
      case 1:
        return MERGE_WRITE_BATCH_NO_WAL;
      case 2:
        return MERGE_SST_INGESTION;
      case 3:
        return MERGE_SST_INGEST_BEHIND;
      default:
        return null;
    }
  }
}
