/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum Operation implements org.apache.thrift.TEnum {
  NOTHING(1),
  PREVIOUS(2),
  CURRENT(3),
  FOR_UPDATE(4),
  EXISTS(5),
  DELTA(6),
  MULTI(7),
  CHANGED(8),
  PREVIOUS_PRESENCE(9);

  private final int value;

  private Operation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Operation findByValue(int value) { 
    switch (value) {
      case 1:
        return NOTHING;
      case 2:
        return PREVIOUS;
      case 3:
        return CURRENT;
      case 4:
        return FOR_UPDATE;
      case 5:
        return EXISTS;
      case 6:
        return DELTA;
      case 7:
        return MULTI;
      case 8:
        return CHANGED;
      case 9:
        return PREVIOUS_PRESENCE;
      default:
        return null;
    }
  }
}
