/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class RangeBudget implements org.apache.thrift.TBase<RangeBudget, RangeBudget._Fields>, java.io.Serializable, Cloneable, Comparable<RangeBudget> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RangeBudget");

  private static final org.apache.thrift.protocol.TField MAX_ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("maxItems", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MAX_BYTES_FIELD_DESC = new org.apache.thrift.protocol.TField("maxBytes", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RangeBudgetStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RangeBudgetTupleSchemeFactory();

  public int maxItems; // required
  public long maxBytes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAX_ITEMS((short)1, "maxItems"),
    MAX_BYTES((short)2, "maxBytes");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAX_ITEMS
          return MAX_ITEMS;
        case 2: // MAX_BYTES
          return MAX_BYTES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MAXITEMS_ISSET_ID = 0;
  private static final int __MAXBYTES_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAX_ITEMS, new org.apache.thrift.meta_data.FieldMetaData("maxItems", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAX_BYTES, new org.apache.thrift.meta_data.FieldMetaData("maxBytes", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RangeBudget.class, metaDataMap);
  }

  public RangeBudget() {
  }

  public RangeBudget(
    int maxItems,
    long maxBytes)
  {
    this();
    this.maxItems = maxItems;
    setMaxItemsIsSet(true);
    this.maxBytes = maxBytes;
    setMaxBytesIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RangeBudget(RangeBudget other) {
    __isset_bitfield = other.__isset_bitfield;
    this.maxItems = other.maxItems;
    this.maxBytes = other.maxBytes;
  }

  @Override
  public RangeBudget deepCopy() {
    return new RangeBudget(this);
  }

  @Override
  public void clear() {
    setMaxItemsIsSet(false);
    this.maxItems = 0;
    setMaxBytesIsSet(false);
    this.maxBytes = 0;
  }

  public int getMaxItems() {
    return this.maxItems;
  }

  public RangeBudget setMaxItems(int maxItems) {
    this.maxItems = maxItems;
    setMaxItemsIsSet(true);
    return this;
  }

  public void unsetMaxItems() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXITEMS_ISSET_ID);
  }

  /** Returns true if field maxItems is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxItems() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXITEMS_ISSET_ID);
  }

  public void setMaxItemsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXITEMS_ISSET_ID, value);
  }

  public long getMaxBytes() {
    return this.maxBytes;
  }

  public RangeBudget setMaxBytes(long maxBytes) {
    this.maxBytes = maxBytes;
    setMaxBytesIsSet(true);
    return this;
  }

  public void unsetMaxBytes() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAXBYTES_ISSET_ID);
  }

  /** Returns true if field maxBytes is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxBytes() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAXBYTES_ISSET_ID);
  }

  public void setMaxBytesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAXBYTES_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MAX_ITEMS:
      if (value == null) {
        unsetMaxItems();
      } else {
        setMaxItems((java.lang.Integer)value);
      }
      break;

    case MAX_BYTES:
      if (value == null) {
        unsetMaxBytes();
      } else {
        setMaxBytes((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MAX_ITEMS:
      return getMaxItems();

    case MAX_BYTES:
      return getMaxBytes();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MAX_ITEMS:
      return isSetMaxItems();
    case MAX_BYTES:
      return isSetMaxBytes();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RangeBudget)
      return this.equals((RangeBudget)that);
    return false;
  }

  public boolean equals(RangeBudget that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_maxItems = true;
    boolean that_present_maxItems = true;
    if (this_present_maxItems || that_present_maxItems) {
      if (!(this_present_maxItems && that_present_maxItems))
        return false;
      if (this.maxItems != that.maxItems)
        return false;
    }

    boolean this_present_maxBytes = true;
    boolean that_present_maxBytes = true;
    if (this_present_maxBytes || that_present_maxBytes) {
      if (!(this_present_maxBytes && that_present_maxBytes))
        return false;
      if (this.maxBytes != that.maxBytes)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + maxItems;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(maxBytes);

    return hashCode;
  }

  @Override
  public int compareTo(RangeBudget other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMaxItems(), other.isSetMaxItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxItems, other.maxItems);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMaxBytes(), other.isSetMaxBytes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxBytes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxBytes, other.maxBytes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RangeBudget(");
    boolean first = true;

    sb.append("maxItems:");
    sb.append(this.maxItems);
    first = false;
    if (!first) sb.append(", ");
    sb.append("maxBytes:");
    sb.append(this.maxBytes);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'maxItems' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'maxBytes' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RangeBudgetStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RangeBudgetStandardScheme getScheme() {
      return new RangeBudgetStandardScheme();
    }
  }

  private static class RangeBudgetStandardScheme extends org.apache.thrift.scheme.StandardScheme<RangeBudget> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RangeBudget struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // MAX_ITEMS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxItems = iprot.readI32();
              struct.setMaxItemsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MAX_BYTES
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.maxBytes = iprot.readI64();
              struct.setMaxBytesIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetMaxItems()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxItems' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetMaxBytes()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxBytes' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RangeBudget struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MAX_ITEMS_FIELD_DESC);
      oprot.writeI32(struct.maxItems);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MAX_BYTES_FIELD_DESC);
      oprot.writeI64(struct.maxBytes);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RangeBudgetTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RangeBudgetTupleScheme getScheme() {
      return new RangeBudgetTupleScheme();
    }
  }

  private static class RangeBudgetTupleScheme extends org.apache.thrift.scheme.TupleScheme<RangeBudget> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RangeBudget struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.maxItems);
      oprot.writeI64(struct.maxBytes);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RangeBudget struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.maxItems = iprot.readI32();
      struct.setMaxItemsIsSet(true);
      struct.maxBytes = iprot.readI64();
      struct.setMaxBytesIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
