/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class RangePage implements org.apache.thrift.TBase<RangePage, RangePage._Fields>, java.io.Serializable, Cloneable, Comparable<RangePage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RangePage");

  private static final org.apache.thrift.protocol.TField ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("items", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField RESUME_AFTER_FIELD_DESC = new org.apache.thrift.protocol.TField("resumeAfter", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField HAS_MORE_FIELD_DESC = new org.apache.thrift.protocol.TField("hasMore", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RangePageStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RangePageTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<KV> items; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.nio.ByteBuffer> resumeAfter; // optional
  public boolean hasMore; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ITEMS((short)1, "items"),
    RESUME_AFTER((short)2, "resumeAfter"),
    HAS_MORE((short)3, "hasMore");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ITEMS
          return ITEMS;
        case 2: // RESUME_AFTER
          return RESUME_AFTER;
        case 3: // HAS_MORE
          return HAS_MORE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HASMORE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.RESUME_AFTER};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ITEMS, new org.apache.thrift.meta_data.FieldMetaData("items", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, KV.class))));
    tmpMap.put(_Fields.RESUME_AFTER, new org.apache.thrift.meta_data.FieldMetaData("resumeAfter", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true))));
    tmpMap.put(_Fields.HAS_MORE, new org.apache.thrift.meta_data.FieldMetaData("hasMore", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RangePage.class, metaDataMap);
  }

  public RangePage() {
  }

  public RangePage(
    java.util.List<KV> items,
    boolean hasMore)
  {
    this();
    this.items = items;
    this.hasMore = hasMore;
    setHasMoreIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RangePage(RangePage other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetItems()) {
      java.util.List<KV> __this__items = new java.util.ArrayList<KV>(other.items.size());
      for (KV other_element : other.items) {
        __this__items.add(new KV(other_element));
      }
      this.items = __this__items;
    }
    if (other.isSetResumeAfter()) {
      java.util.List<java.nio.ByteBuffer> __this__resumeAfter = new java.util.ArrayList<java.nio.ByteBuffer>(other.resumeAfter);
      this.resumeAfter = __this__resumeAfter;
    }
    this.hasMore = other.hasMore;
  }

  @Override
  public RangePage deepCopy() {
    return new RangePage(this);
  }

  @Override
  public void clear() {
    this.items = null;
    this.resumeAfter = null;
    setHasMoreIsSet(false);
    this.hasMore = false;
  }

  public int getItemsSize() {
    return (this.items == null) ? 0 : this.items.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<KV> getItemsIterator() {
    return (this.items == null) ? null : this.items.iterator();
  }

  public void addToItems(KV elem) {
    if (this.items == null) {
      this.items = new java.util.ArrayList<KV>();
    }
    this.items.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<KV> getItems() {
    return this.items;
  }

  public RangePage setItems(@org.apache.thrift.annotation.Nullable java.util.List<KV> items) {
    this.items = items;
    return this;
  }

  public void unsetItems() {
    this.items = null;
  }

  /** Returns true if field items is set (has been assigned a value) and false otherwise */
  public boolean isSetItems() {
    return this.items != null;
  }

  public void setItemsIsSet(boolean value) {
    if (!value) {
      this.items = null;
    }
  }

  public int getResumeAfterSize() {
    return (this.resumeAfter == null) ? 0 : this.resumeAfter.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.nio.ByteBuffer> getResumeAfterIterator() {
    return (this.resumeAfter == null) ? null : this.resumeAfter.iterator();
  }

  public void addToResumeAfter(java.nio.ByteBuffer elem) {
    if (this.resumeAfter == null) {
      this.resumeAfter = new java.util.ArrayList<java.nio.ByteBuffer>();
    }
    this.resumeAfter.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.nio.ByteBuffer> getResumeAfter() {
    return this.resumeAfter;
  }

  public RangePage setResumeAfter(@org.apache.thrift.annotation.Nullable java.util.List<java.nio.ByteBuffer> resumeAfter) {
    this.resumeAfter = resumeAfter;
    return this;
  }

  public void unsetResumeAfter() {
    this.resumeAfter = null;
  }

  /** Returns true if field resumeAfter is set (has been assigned a value) and false otherwise */
  public boolean isSetResumeAfter() {
    return this.resumeAfter != null;
  }

  public void setResumeAfterIsSet(boolean value) {
    if (!value) {
      this.resumeAfter = null;
    }
  }

  public boolean isHasMore() {
    return this.hasMore;
  }

  public RangePage setHasMore(boolean hasMore) {
    this.hasMore = hasMore;
    setHasMoreIsSet(true);
    return this;
  }

  public void unsetHasMore() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __HASMORE_ISSET_ID);
  }

  /** Returns true if field hasMore is set (has been assigned a value) and false otherwise */
  public boolean isSetHasMore() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __HASMORE_ISSET_ID);
  }

  public void setHasMoreIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __HASMORE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ITEMS:
      if (value == null) {
        unsetItems();
      } else {
        setItems((java.util.List<KV>)value);
      }
      break;

    case RESUME_AFTER:
      if (value == null) {
        unsetResumeAfter();
      } else {
        setResumeAfter((java.util.List<java.nio.ByteBuffer>)value);
      }
      break;

    case HAS_MORE:
      if (value == null) {
        unsetHasMore();
      } else {
        setHasMore((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ITEMS:
      return getItems();

    case RESUME_AFTER:
      return getResumeAfter();

    case HAS_MORE:
      return isHasMore();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ITEMS:
      return isSetItems();
    case RESUME_AFTER:
      return isSetResumeAfter();
    case HAS_MORE:
      return isSetHasMore();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RangePage)
      return this.equals((RangePage)that);
    return false;
  }

  public boolean equals(RangePage that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_items = true && this.isSetItems();
    boolean that_present_items = true && that.isSetItems();
    if (this_present_items || that_present_items) {
      if (!(this_present_items && that_present_items))
        return false;
      if (!this.items.equals(that.items))
        return false;
    }

    boolean this_present_resumeAfter = true && this.isSetResumeAfter();
    boolean that_present_resumeAfter = true && that.isSetResumeAfter();
    if (this_present_resumeAfter || that_present_resumeAfter) {
      if (!(this_present_resumeAfter && that_present_resumeAfter))
        return false;
      if (!this.resumeAfter.equals(that.resumeAfter))
        return false;
    }

    boolean this_present_hasMore = true;
    boolean that_present_hasMore = true;
    if (this_present_hasMore || that_present_hasMore) {
      if (!(this_present_hasMore && that_present_hasMore))
        return false;
      if (this.hasMore != that.hasMore)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetItems()) ? 131071 : 524287);
    if (isSetItems())
      hashCode = hashCode * 8191 + items.hashCode();

    hashCode = hashCode * 8191 + ((isSetResumeAfter()) ? 131071 : 524287);
    if (isSetResumeAfter())
      hashCode = hashCode * 8191 + resumeAfter.hashCode();

    hashCode = hashCode * 8191 + ((hasMore) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(RangePage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetItems(), other.isSetItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.items, other.items);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetResumeAfter(), other.isSetResumeAfter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResumeAfter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resumeAfter, other.resumeAfter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHasMore(), other.isSetHasMore());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHasMore()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hasMore, other.hasMore);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RangePage(");
    boolean first = true;

    sb.append("items:");
    if (this.items == null) {
      sb.append("null");
    } else {
      sb.append(this.items);
    }
    first = false;
    if (isSetResumeAfter()) {
      if (!first) sb.append(", ");
      sb.append("resumeAfter:");
      if (this.resumeAfter == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.resumeAfter, sb);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("hasMore:");
    sb.append(this.hasMore);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (items == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'items' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'hasMore' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RangePageStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RangePageStandardScheme getScheme() {
      return new RangePageStandardScheme();
    }
  }

  private static class RangePageStandardScheme extends org.apache.thrift.scheme.StandardScheme<RangePage> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RangePage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // ITEMS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
                struct.items = new java.util.ArrayList<KV>(_list40.size);
                @org.apache.thrift.annotation.Nullable KV _elem41;
                for (int _i42 = 0; _i42 < _list40.size; ++_i42)
                {
                  _elem41 = new KV();
                  _elem41.read(iprot);
                  struct.items.add(_elem41);
                }
                iprot.readListEnd();
              }
              struct.setItemsIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESUME_AFTER
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list43 = iprot.readListBegin();
                struct.resumeAfter = new java.util.ArrayList<java.nio.ByteBuffer>(_list43.size);
                @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer _elem44;
                for (int _i45 = 0; _i45 < _list43.size; ++_i45)
                {
                  _elem44 = iprot.readBinary();
                  struct.resumeAfter.add(_elem44);
                }
                iprot.readListEnd();
              }
              struct.setResumeAfterIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // HAS_MORE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.hasMore = iprot.readBool();
              struct.setHasMoreIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHasMore()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'hasMore' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RangePage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.items != null) {
        oprot.writeFieldBegin(ITEMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.items.size()));
          for (KV _iter46 : struct.items)
          {
            _iter46.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.resumeAfter != null) {
        if (struct.isSetResumeAfter()) {
          oprot.writeFieldBegin(RESUME_AFTER_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.resumeAfter.size()));
            for (java.nio.ByteBuffer _iter47 : struct.resumeAfter)
            {
              oprot.writeBinary(_iter47);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(HAS_MORE_FIELD_DESC);
      oprot.writeBool(struct.hasMore);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RangePageTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RangePageTupleScheme getScheme() {
      return new RangePageTupleScheme();
    }
  }

  private static class RangePageTupleScheme extends org.apache.thrift.scheme.TupleScheme<RangePage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RangePage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        oprot.writeI32(struct.items.size());
        for (KV _iter48 : struct.items)
        {
          _iter48.write(oprot);
        }
      }
      oprot.writeBool(struct.hasMore);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetResumeAfter()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetResumeAfter()) {
        {
          oprot.writeI32(struct.resumeAfter.size());
          for (java.nio.ByteBuffer _iter49 : struct.resumeAfter)
          {
            oprot.writeBinary(_iter49);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RangePage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list50 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
        struct.items = new java.util.ArrayList<KV>(_list50.size);
        @org.apache.thrift.annotation.Nullable KV _elem51;
        for (int _i52 = 0; _i52 < _list50.size; ++_i52)
        {
          _elem51 = new KV();
          _elem51.read(iprot);
          struct.items.add(_elem51);
        }
      }
      struct.setItemsIsSet(true);
      struct.hasMore = iprot.readBool();
      struct.setHasMoreIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list53 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.resumeAfter = new java.util.ArrayList<java.nio.ByteBuffer>(_list53.size);
          @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer _elem54;
          for (int _i55 = 0; _i55 < _list53.size; ++_i55)
          {
            _elem54 = iprot.readBinary();
            struct.resumeAfter.add(_elem54);
          }
        }
        struct.setResumeAfterIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
