/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum RangeRequestType implements org.apache.thrift.TEnum {
  ALL_IN_RANGE(1),
  ALL_IN_RANGE_NO_CACHE(2);

  private final int value;

  private RangeRequestType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RangeRequestType findByValue(int value) {
    switch (value) {
      case 1:
        return ALL_IN_RANGE;
      case 2:
        return ALL_IN_RANGE_NO_CACHE;
      default:
        return null;
    }
  }
}
