/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class RequestContext implements org.apache.thrift.TBase<RequestContext, RequestContext._Fields>, java.io.Serializable, Cloneable, Comparable<RequestContext> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RequestContext");

  private static final org.apache.thrift.protocol.TField PROFILE_FIELD_DESC = new org.apache.thrift.protocol.TField("profile", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField WORKLOAD_CONTRACT_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("workloadContractVersion", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField TIMEOUT_NANOS_FIELD_DESC = new org.apache.thrift.protocol.TField("timeoutNanos", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RequestContextStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RequestContextTupleSchemeFactory();

  /**
   *
   * @see WorkloadProfile
   */
  public @org.apache.thrift.annotation.Nullable WorkloadProfile profile; // required
  public int workloadContractVersion; // required
  public long timeoutNanos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     *
     * @see WorkloadProfile
     */
    PROFILE((short)1, "profile"),
    WORKLOAD_CONTRACT_VERSION((short)3, "workloadContractVersion"),
    TIMEOUT_NANOS((short)4, "timeoutNanos");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROFILE
          return PROFILE;
        case 3: // WORKLOAD_CONTRACT_VERSION
          return WORKLOAD_CONTRACT_VERSION;
        case 4: // TIMEOUT_NANOS
          return TIMEOUT_NANOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WORKLOADCONTRACTVERSION_ISSET_ID = 0;
  private static final int __TIMEOUTNANOS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROFILE, new org.apache.thrift.meta_data.FieldMetaData("profile", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, WorkloadProfile.class)));
    tmpMap.put(_Fields.WORKLOAD_CONTRACT_VERSION, new org.apache.thrift.meta_data.FieldMetaData("workloadContractVersion", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TIMEOUT_NANOS, new org.apache.thrift.meta_data.FieldMetaData("timeoutNanos", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RequestContext.class, metaDataMap);
  }

  public RequestContext() {
  }

  public RequestContext(
    WorkloadProfile profile,
    int workloadContractVersion,
    long timeoutNanos)
  {
    this();
    this.profile = profile;
    this.workloadContractVersion = workloadContractVersion;
    setWorkloadContractVersionIsSet(true);
    this.timeoutNanos = timeoutNanos;
    setTimeoutNanosIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RequestContext(RequestContext other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetProfile()) {
      this.profile = other.profile;
    }
    this.workloadContractVersion = other.workloadContractVersion;
    this.timeoutNanos = other.timeoutNanos;
  }

  @Override
  public RequestContext deepCopy() {
    return new RequestContext(this);
  }

  @Override
  public void clear() {
    this.profile = null;
    setWorkloadContractVersionIsSet(false);
    this.workloadContractVersion = 0;
    setTimeoutNanosIsSet(false);
    this.timeoutNanos = 0;
  }

  /**
   *
   * @see WorkloadProfile
   */
  @org.apache.thrift.annotation.Nullable
  public WorkloadProfile getProfile() {
    return this.profile;
  }

  /**
   *
   * @see WorkloadProfile
   */
  public RequestContext setProfile(@org.apache.thrift.annotation.Nullable WorkloadProfile profile) {
    this.profile = profile;
    return this;
  }

  public void unsetProfile() {
    this.profile = null;
  }

  /** Returns true if field profile is set (has been assigned a value) and false otherwise */
  public boolean isSetProfile() {
    return this.profile != null;
  }

  public void setProfileIsSet(boolean value) {
    if (!value) {
      this.profile = null;
    }
  }

  public int getWorkloadContractVersion() {
    return this.workloadContractVersion;
  }

  public RequestContext setWorkloadContractVersion(int workloadContractVersion) {
    this.workloadContractVersion = workloadContractVersion;
    setWorkloadContractVersionIsSet(true);
    return this;
  }

  public void unsetWorkloadContractVersion() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WORKLOADCONTRACTVERSION_ISSET_ID);
  }

  /** Returns true if field workloadContractVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetWorkloadContractVersion() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WORKLOADCONTRACTVERSION_ISSET_ID);
  }

  public void setWorkloadContractVersionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WORKLOADCONTRACTVERSION_ISSET_ID, value);
  }

  public long getTimeoutNanos() {
    return this.timeoutNanos;
  }

  public RequestContext setTimeoutNanos(long timeoutNanos) {
    this.timeoutNanos = timeoutNanos;
    setTimeoutNanosIsSet(true);
    return this;
  }

  public void unsetTimeoutNanos() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMEOUTNANOS_ISSET_ID);
  }

  /** Returns true if field timeoutNanos is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeoutNanos() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMEOUTNANOS_ISSET_ID);
  }

  public void setTimeoutNanosIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMEOUTNANOS_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PROFILE:
      if (value == null) {
        unsetProfile();
      } else {
        setProfile((WorkloadProfile)value);
      }
      break;

    case WORKLOAD_CONTRACT_VERSION:
      if (value == null) {
        unsetWorkloadContractVersion();
      } else {
        setWorkloadContractVersion((java.lang.Integer)value);
      }
      break;

    case TIMEOUT_NANOS:
      if (value == null) {
        unsetTimeoutNanos();
      } else {
        setTimeoutNanos((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PROFILE:
      return getProfile();

    case WORKLOAD_CONTRACT_VERSION:
      return getWorkloadContractVersion();

    case TIMEOUT_NANOS:
      return getTimeoutNanos();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PROFILE:
      return isSetProfile();
    case WORKLOAD_CONTRACT_VERSION:
      return isSetWorkloadContractVersion();
    case TIMEOUT_NANOS:
      return isSetTimeoutNanos();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RequestContext)
      return this.equals((RequestContext)that);
    return false;
  }

  public boolean equals(RequestContext that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_profile = true && this.isSetProfile();
    boolean that_present_profile = true && that.isSetProfile();
    if (this_present_profile || that_present_profile) {
      if (!(this_present_profile && that_present_profile))
        return false;
      if (!this.profile.equals(that.profile))
        return false;
    }

    boolean this_present_workloadContractVersion = true;
    boolean that_present_workloadContractVersion = true;
    if (this_present_workloadContractVersion || that_present_workloadContractVersion) {
      if (!(this_present_workloadContractVersion && that_present_workloadContractVersion))
        return false;
      if (this.workloadContractVersion != that.workloadContractVersion)
        return false;
    }

    boolean this_present_timeoutNanos = true;
    boolean that_present_timeoutNanos = true;
    if (this_present_timeoutNanos || that_present_timeoutNanos) {
      if (!(this_present_timeoutNanos && that_present_timeoutNanos))
        return false;
      if (this.timeoutNanos != that.timeoutNanos)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetProfile()) ? 131071 : 524287);
    if (isSetProfile())
      hashCode = hashCode * 8191 + profile.getValue();

    hashCode = hashCode * 8191 + workloadContractVersion;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timeoutNanos);

    return hashCode;
  }

  @Override
  public int compareTo(RequestContext other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetProfile(), other.isSetProfile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProfile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.profile, other.profile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetWorkloadContractVersion(), other.isSetWorkloadContractVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWorkloadContractVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.workloadContractVersion, other.workloadContractVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTimeoutNanos(), other.isSetTimeoutNanos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeoutNanos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeoutNanos, other.timeoutNanos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RequestContext(");
    boolean first = true;

    sb.append("profile:");
    if (this.profile == null) {
      sb.append("null");
    } else {
      sb.append(this.profile);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("workloadContractVersion:");
    sb.append(this.workloadContractVersion);
    first = false;
    if (!first) sb.append(", ");
    sb.append("timeoutNanos:");
    sb.append(this.timeoutNanos);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (profile == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'profile' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'workloadContractVersion' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'timeoutNanos' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RequestContextStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RequestContextStandardScheme getScheme() {
      return new RequestContextStandardScheme();
    }
  }

  private static class RequestContextStandardScheme extends org.apache.thrift.scheme.StandardScheme<RequestContext> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RequestContext struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // PROFILE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.profile = it.cavallium.rockserver.core.common.api.WorkloadProfile.findByValue(iprot.readI32());
              struct.setProfileIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // WORKLOAD_CONTRACT_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.workloadContractVersion = iprot.readI32();
              struct.setWorkloadContractVersionIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TIMEOUT_NANOS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timeoutNanos = iprot.readI64();
              struct.setTimeoutNanosIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetWorkloadContractVersion()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'workloadContractVersion' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTimeoutNanos()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timeoutNanos' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RequestContext struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.profile != null) {
        oprot.writeFieldBegin(PROFILE_FIELD_DESC);
        oprot.writeI32(struct.profile.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(WORKLOAD_CONTRACT_VERSION_FIELD_DESC);
      oprot.writeI32(struct.workloadContractVersion);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TIMEOUT_NANOS_FIELD_DESC);
      oprot.writeI64(struct.timeoutNanos);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RequestContextTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RequestContextTupleScheme getScheme() {
      return new RequestContextTupleScheme();
    }
  }

  private static class RequestContextTupleScheme extends org.apache.thrift.scheme.TupleScheme<RequestContext> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RequestContext struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.profile.getValue());
      oprot.writeI32(struct.workloadContractVersion);
      oprot.writeI64(struct.timeoutNanos);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RequestContext struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.profile = it.cavallium.rockserver.core.common.api.WorkloadProfile.findByValue(iprot.readI32());
      struct.setProfileIsSet(true);
      struct.workloadContractVersion = iprot.readI32();
      struct.setWorkloadContractVersionIsSet(true);
      struct.timeoutNanos = iprot.readI64();
      struct.setTimeoutNanosIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}
