/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum RocksDBErrorType implements org.apache.thrift.TEnum {
  PUT_UNKNOWN_ERROR(0),
  PUT_2(1),
  UNEXPECTED_NULL_VALUE(2),
  PUT_1(3),
  PUT_3(4),
  GET_1(5),
  COLUMN_EXISTS(6),
  COLUMN_CREATE_FAIL(7),
  COLUMN_NOT_FOUND(8),
  COLUMN_DELETE_FAIL(9),
  CONFIG_ERROR(10),
  ROCKSDB_CONFIG_ERROR(11),
  VALUE_MUST_BE_NULL(12),
  DIRECTORY_DELETE(13),
  KEY_LENGTH_MISMATCH(14),
  UNSUPPORTED_HASH_SIZE(15),
  RAW_KEY_LENGTH_MISMATCH(16),
  KEYS_COUNT_MISMATCH(17),
  COMMIT_FAILED_TRY_AGAIN(18),
  COMMIT_FAILED(19),
  TX_NOT_FOUND(20),
  KEY_HASH_SIZE_MISMATCH(21),
  RESTRICTED_TRANSACTION(22),
  PUT_INVALID_REQUEST(23),
  UPDATE_RETRY(24),
  ROCKSDB_LOAD_ERROR(25),
  WRITE_BATCH_1(26),
  SST_WRITE_1(27),
  SST_WRITE_2(28),
  SST_WRITE_3(29),
  SST_WRITE_4(30),
  SST_GET_SIZE_FAILED(31),
  UNSUPPORTED_COLUMN_TYPE(32),
  NOT_IMPLEMENTED(33),
  GET_PROPERTY_ERROR(34),
  INTERNAL_ERROR(35),
  TRANSACTION_NOT_FOUND(36),
  NULL_ARGUMENT(37);

  private final int value;

  private RocksDBErrorType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RocksDBErrorType findByValue(int value) { 
    switch (value) {
      case 0:
        return PUT_UNKNOWN_ERROR;
      case 1:
        return PUT_2;
      case 2:
        return UNEXPECTED_NULL_VALUE;
      case 3:
        return PUT_1;
      case 4:
        return PUT_3;
      case 5:
        return GET_1;
      case 6:
        return COLUMN_EXISTS;
      case 7:
        return COLUMN_CREATE_FAIL;
      case 8:
        return COLUMN_NOT_FOUND;
      case 9:
        return COLUMN_DELETE_FAIL;
      case 10:
        return CONFIG_ERROR;
      case 11:
        return ROCKSDB_CONFIG_ERROR;
      case 12:
        return VALUE_MUST_BE_NULL;
      case 13:
        return DIRECTORY_DELETE;
      case 14:
        return KEY_LENGTH_MISMATCH;
      case 15:
        return UNSUPPORTED_HASH_SIZE;
      case 16:
        return RAW_KEY_LENGTH_MISMATCH;
      case 17:
        return KEYS_COUNT_MISMATCH;
      case 18:
        return COMMIT_FAILED_TRY_AGAIN;
      case 19:
        return COMMIT_FAILED;
      case 20:
        return TX_NOT_FOUND;
      case 21:
        return KEY_HASH_SIZE_MISMATCH;
      case 22:
        return RESTRICTED_TRANSACTION;
      case 23:
        return PUT_INVALID_REQUEST;
      case 24:
        return UPDATE_RETRY;
      case 25:
        return ROCKSDB_LOAD_ERROR;
      case 26:
        return WRITE_BATCH_1;
      case 27:
        return SST_WRITE_1;
      case 28:
        return SST_WRITE_2;
      case 29:
        return SST_WRITE_3;
      case 30:
        return SST_WRITE_4;
      case 31:
        return SST_GET_SIZE_FAILED;
      case 32:
        return UNSUPPORTED_COLUMN_TYPE;
      case 33:
        return NOT_IMPLEMENTED;
      case 34:
        return GET_PROPERTY_ERROR;
      case 35:
        return INTERNAL_ERROR;
      case 36:
        return TRANSACTION_NOT_FOUND;
      case 37:
        return NULL_ARGUMENT;
      default:
        return null;
    }
  }
}
