/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum WorkloadProfile implements org.apache.thrift.TEnum {
  CONTROL(1),
  LATENCY(2),
  ANALYTICAL(3),
  INGEST(4),
  CDC(5),
  BATCH(6),
  PHYSICAL_MAINTENANCE(7);

  private final int value;

  private WorkloadProfile(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static WorkloadProfile findByValue(int value) {
    switch (value) {
      case 1:
        return CONTROL;
      case 2:
        return LATENCY;
      case 3:
        return ANALYTICAL;
      case 4:
        return INGEST;
      case 5:
        return CDC;
      case 6:
        return BATCH;
      case 7:
        return PHYSICAL_MAINTENANCE;
      default:
        return null;
    }
  }
}
