/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package it.cavallium.rockserver.core.common.api;


public enum WriteClass implements org.apache.thrift.TEnum {
  FOREGROUND(0),
  MAINTENANCE(1);

  private final int value;

  private WriteClass(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static WriteClass findByValue(int value) {
    switch (value) {
      case 0:
        return FOREGROUND;
      case 1:
        return MAINTENANCE;
      default:
        return null;
    }
  }
}
